---
title: ODAP Project Review Panel (PRP) Terms of Reference v0.51
---

# Role and responsibility

To ensure compliance with the 5 safes, particularly **safe projects** - providing scientific review for applications for data use and approve/refer/reject data access requests for the Outbreak Data Analysis Platform.

The PRP will be provided with a short due diligence report from the ODAP secretariat, containing:

- confirmation of *bona fide* researcher status for the applicant(s)
- confirmation that requested data exists, that the ODAP team has data controllership, and that data is not under embargo
- assessment of fit with ODAP scope: within scope/uncertain/not within scope
- assessment of lay summary and public involvement: adequate/not adequate
- a list of any potential overlapping or duplicate projects already approved or proposed

For each project, three scientific reviewers will provide an opinion on:

-   Scientific quality
-   Feasibility
-   Fit within ODAP scope and potentialy for benefit to patients or the public
-   Degree of overlap and redundancy with other projects already approved or proposed

The PRP may seek advice from the ODAP Data Access Governance Committee (DAGC), where appropriate, for potentially complex and challenging proposals and data access requests.

The PRP will consider these reports for each project and provide an opinion from one of the following options: approved/rejected/refer to DAGC.

# Ways of working

## Reporting

The ODAP secretariat will openly report applications, reviews and outcomes for each application on the ODAP website. 

For each onward sharing of linked NHS Digital data, ODAP secretariat will report information about the dissemination on the NHS Digital release register. This will include the name of the organisation(s) accessing the data, the purpose (summary of the project) and details of the data released.

## Meeting modality and frequency

Meetings will occur on an ad hoc basis when needed. Discussions may be conducted and resolved by email without meeting at the discretion of the Chair. Frequency of meetings will be arranged according to the volume of applications.

## Meeting content and quorum

Meetings consider applications, risks and issues arising of concern to the ODAP Project Review Panel and its responsibilities. All members are invited to comment and the meeting is quorate if five members are in attendance including one of the Chair or Deputy Chair.

The ODAP secretariat is responsible for arranging the meeting and setting an agenda.

## Responsibilities of the Panel Chair

The Chair is responsible for chairing the meeting and ensuring an accurate record of the decision-making is made. The Chair will be supported by the ODAP secretariat. All panel members have an opportunity to review and challenge the meeting record. The meeting records will be made public on the ODAP website: [odap.ac.uk](https://odap.ac.uk)

## Conflicts of interest

Panel members who are involved in an application, or who have a direct personal or professional relationship with an applicant, will be expected to declare this to the panel and recuse themselves from discussion of the application.

## Amendment process

Amendments to approved applications may be considered by the Project Review Panel Chair and/or Deputy Chair out of meetings. Non-contentious simple amendments (such as the addition of a new researcher in a team, or the incremental addition of new relevant data items within a similar scope and sensitivity of the original application) may be approved by the Chair and/or Deputy without further consultation. 

## Appeal process

Rejected applications are permitted to appeal a decision of the PRP once. Comments, questions and criticisms generated during the ODAP review process must be addressed fully by the applicants in order for the appeal to be considered. 

## Terms of reference and review of processes

The outlined processes will be reviewed on a regular basis by the ODAP secretariat and changed based on the practical implications proposed by the Project Review Panel. 

# Members

- Chair - ODAP scientific manager
- Deputy Chair - appointed from the members of the committee
- Support - ODAP secretariat 
- 3 lay members
- Three scientific reviewers, drawn from the members from each of the various consortia contributing data to the ODAP will be sought on a rotational basis. 
- Representatives from each of the contributing academic studies






