---
title: ODAP Partnership Steering Group v0.11
---

# Terms of Reference

## Outbreak Data Analysis Platform (ODAP) Scope

The purpose of the ODAP is to facilitate biomedical research to advance understanding of severe infectious disease and other exposures of public health interest. Research within the ODAP is strictly limited to this purpose.

\* Severe infectious disease - this term describes all severe infectious agents, including new, re-emerging or therapy-resistant forms of existing infectious agents.

\*\* Other exposures of public health interest: this term describes new or unexplained poisoning, or exposure to harmful energy sources such as electromagnetic radiation.

## ODAP Governance Structures

- ODAP Delivery Group (University of Edinburgh team) is responsible for operational delivery, and provides the secretariat for ODAP Partnership Steering Group, ODAP Data Access Governance Committee, and ODAP Project Review Panel.
- University of Edinburgh (as the lead institution for ODAP) is accountable to the funders for delivery.
- ODAP Partnership Steering Group to provide strategic guidance, support, and challenge to ODAP delivery team, data contributors, and associated partners to ensure delivery.
- ODAP Data Access Governance Committee to approve data access governance processes for non-embargoed data.
- ODAP Project Review Panel to review and approve individual applications to ODAP for access to non-embargoed data.

## ODAP Partnership Steering Group Role

The Outbreak Data Analysis Platform Partnership Steering Group supports the development of the Outbreak Data Analysis Platform by providing strategic direction. The Partnership Steering Group will provide support, guidance, and oversight of the development of the Outbreak Data Analysis Platform and will not be involved in the operational delivery of the platform.

The ODAP Partnership Steering Group will:

-   Provide support to the data infrastructure development for the ODAP

-   Support direction of research permitted access to ODAP

-   Provide strategic direction for the onboarding of additional datasets and provide updates on progress of onboarding datasets already identified.

-   Provide advice for patient and public involvement in the project

-   Provide challenge to the project strategy where appropriate

-   Act as champions for the ODAP platform and strengthen the relationship between academia and public health agencies

-   Ensures the development of ODAP is aligned with agreed funding terms from HDRUK

-   Provide advice and guidance to ensure sustainability of ODAP beyond HDRUK funding terms

-   Assist with resolving strategic level risks to delivery

## Fixed Agenda

-   Update on progress against deliverables and risk register review

    a.  Dataset onboarding

    b.  Data access and governance

    c.  PPIE

-   Finances against contract and future sustainability

-   Partnership Steering group members updates if necessary

-   AOB

All agenda items to have named person from ODAP delivery group to speak for.

## Frequency

1 hour meeting each quarter, starting October 2022 until dissolved by ODAP Delivery Group.

## Responsibilities of the ODAP Partnership Steering Group Chair

The ODAP Partnership Steering Group Chair and Deputy Chair (or two co-chairs) will be nominated by the ODAP Partnerthip Steering Group. The Chair and Deputy Chair will be supported heavily by the ODAP Delivery Team.

## The ODAP Partnership Steering Group Chair(s) will remain in post for 2 years, before the partnership steering group nominates a new chair.

The ODAPP Partnership Steering Group Chair(s) will:

-   Work with the ODAP Delivery Group to set a fixed agenda

-   Makes the purpose of each meeting clear to members and explains the agenda at the beginning of each meeting

-   Clarify and summarise what is happening throughout each meeting.

-   Keeps the meeting moving by putting time limits on each agenda items and ensuring meetings finish on time.

-   Encourages broad participation from members in discussion by calling on different people.

-   End each meeting with a summary of decisions and assignments.

-   Follow up with consistently absent members to determine if they wish to discontinue membership.

-   Find replacements for members who discontinue participation (with support from the ODAP Delivery Team).

-   Manage the voting process if the group does not reach a consensus

-   Liaise with absent members via email to ensure group aware of decisions made.

## Ways of Working

-   The group will meet quarterly until otherwise agreed

-   Agenda and papers will be shared 1 week before the meeting by the ODAP Delivery Team.

-   Actions and notes will be captured by the ODAP Delivery Team and shared within 5 days after the meeting.

-   Meeting minutes will be published on the ODAP website

-   Members may be contacted between meetings for advice and support for delivery.

-   Decisions will be made by consensus. Where this is not possible a vote will be taken with a majority win. In the event of a tie, the Chair will decide.

-   ODAP Delivery Team provide the secretariat for the ODAP Partnership Steering Group

-   Chair's brief to be held 1 week before to discuss agenda and issues arising

## Quorum

The ODAP Partnertship Steering Group will be quorate to make decisions when 40% of voting members are present. If 40% of voting members are not present, the Chair will gather a decision via email.

## Membership

Members of the ODAP Partnership Steering Group include representatives from the data contributors who share data with the Outbreak Data Analysis Platform, public health agencies from across the four nations, and other representatives who have supported ODAP's development, including funders.

## Voting members

Voting members will include data contributors, public health agencies and funders. Each of these organisations will nominate a single representative to be responsible for their vote.

  ---------------------------------------------------------------------------------------
  **Organisation**                                      **Nominated attendee(s)**
  ----------------------------------------------------- ---------------------------------
  ODAP Chief Investigator/University of Edinburgh       Kenny Baillie

  Edinburgh Parallel Computing Centre                   Mark Parsons/Rob Baxter

  COVID-19 Genomics UK Consortium (COG-UK)              Sharon Peacock

  ICNARC                                                Kathy Rowan

  ISARIC4C                                              Calum Semple

  GenOMICC                                              Clark Russel

  PHOSP-COVID                                           Louise Wain

  HEAL-COVID                                            Charlotte Summers

  NHS Digital                                           Michael Chapman

  CLIMB-COVID                                           Tom Connor

  UKHSA                                                 Johanna Hutchinson/Ian Harrison

  Public Health Scotland                                Carole Morris

  Health and Social Care Northern Ireland               Ian Young/Declan Bradley

  Welsh Government                                      Fliss Benee

  Health Data Research UK                               Andrew Morris
  ---------------------------------------------------------------------------------------

## Non-voting operational/advisory members

+-------------------------------------------------------------+---------------------------+
| **Organisation**                                            | **Nominated attendee(s)** |
+=============================================================+===========================+
| University of Edinburgh                                     | ODAP secretariat          |
+-------------------------------------------------------------+---------------------------+
| ICNARC                                                      | David Harrison            |
+-------------------------------------------------------------+---------------------------+
| UKHSA                                                       | Tariq Malik               |
+-------------------------------------------------------------+---------------------------+
| NHS Digital                                                 | Helen Buckels             |
+-------------------------------------------------------------+---------------------------+
| Public Health Scotland                                      | Matt Holden               |
+-------------------------------------------------------------+---------------------------+
| Office for National Statistics                              | Peter Stokes              |
+-------------------------------------------------------------+---------------------------+
| UK Longitudinal Linkage Collaboration                       | Andy Boyd                 |
+-------------------------------------------------------------+---------------------------+
| British Heart Foundation Data Science Centre                | Cathie Sudlow             |
+-------------------------------------------------------------+---------------------------+




