---
title: ODAP Data Access Governance Committee
version: 0.81
---

# Terms of Reference

## Role of the ODAP DAGC

To approve the ODAP information governance processes proposed by the Lead Institute (the University of Edinburgh). This includes approving:

-   Scope of research within the ODAP non embargo area. Changes to scope are proposed by the steering group and approved by the DAGC.
-   Defining limits of scope for streamlined access to data in the non-embargo area.
-   Oversight of data governance processes used by the Lead Institute to manage the data access including the assessment criteria for access requests in the non-embargo area
-   Processes for output review
-   Transparency and publication policies
-   All other aspects of ODAP data access governance
-   Where the Lead Institute via the ODAP secretariat or the Data Contributor wish to obtain a second opinion on whether a request falls within the scope of ODAP, or where an applicant appeals against a decision, the request can be referred to ODAP DAGC who review access request material and return their advice to the Data Contributor and Lead Institute.

## Membership

The membership structure of ODAP DAGC is defined by the ODAP Steering Group. The starting membership structure includes all data contributors to the Outbreak Data Analysis Platform, representatives from the four national Public Health Agencies, lay representatives and other non-lay members. Each organisation should nominate a lead representative to join the DAGC. Prospective data contributors may be invited to attend meetings as an observer until their datasets are approved for on boarding into ODAP. The dataset on boarding policy and process are to be defined and agreed by the ODAP steering committee. Nominations and names of DAGC members can be found in the Annex below.

1.  **Eligibility:** Members must agree to abide by the terms of reference and conflict of interest policy set out in this document.

2.  **Term:** DAGC members can hold their position for 3 years and can be re-elected for a maximum of 3 terms.

3.  **Resignation:** Members are free to resign their position with immediate effect. Where possible, 3 months' notice should be given.

4.  **Revocation:** Membership to the DAGC can be revoked by the ODAP Steering Group for professional misconduct and/or a breach of the platform governance framework. DAGC members are asked to be active in their participation on the Committee. Members who participate in less than 20% of DAGC activities within a 6-month period may be asked to reconsider their involvement in the DAGC.

## Responsibilities of the ODAP DAGC Chair

1.  The Chair has responsibility for ensuring that any conflicts of interest are recognised and appropriately managed.

2.  The Chair will ensure that ODAP DAGC members are not put under pressure to approve or reject proposed information governance processes, assessment criteria or any queried applications based on any vested interests or conflicts of interest, and that applications are considered solely against the stated scope criteria of the ODAP DAGC.

3.  A Vice Chair will also be appointed, who will take over the duties of the Chair in the event that the Chair is unavailable. Apart from covering for the Chair, the Vice Chair has no other additional duties.

4.  Any member of the ODAP DAGC who isn't affiliated with a funder (i.e. UKRI, HDRUK), the Lead Institute (i.e. the University of Edinburgh) or data contributors can put themselves forward to act as Chair or Vice Chair. In the event of more than one nomination being received for the position, the ODAP DAGC members will vote, with the candidate with the majority of votes being elected to the position.

5.  The tenure of the Chair and Vice Chair will normally be for 3 years renewable with the rest of ODAP DAGC's agreement. A Chair or Vice Chair may seek re-election to the role after this period if they wish to do so. Either may resign their position at any stage if they are unable or unwilling to continue. If the Chair or Vice Chair are not performing their duties appropriately, the chair of ODAP steering group may ask the ODAP DAGC for permission (by majority vote) to remove them and hold a vote to appoint a replacement.

## Meeting frequency

1.  Following on from a period of initial meetings to establish ODAP data access governance processes, ODAP DAGC will convene for 6 monthly regular videoconference meetings to review how ODAP data access is functioning (as described in section 7 below), discuss any issues the Lead Institute wishes to raise, and carry out the other functions described in their role. Regular meetings will be scheduled 12 months in advance.

2.  When asked by the Lead Institute to review material (proposals for access governance processes or other requests such as review of an application) DAGC members will return their reviews to the Secretariat via email.

3.  ODAP steering group or Lead Institute may also request more extraordinary convening of ODAP DAGC

## Quorum

1.  To be quorate, regular ODAP DAGC meetings should include at least 3 members from the data contributor group, and one member from each other membership group (public health agencies, other scientific members and lay members) as well as a senior representative of the Lead Institute (i.e. the University of Edinburgh).

## Conflicts of interest

1.  Definition: These terms define \"conflict of interest\" as any interest that may affect or reasonably be perceived to affect individual objectivity and independence in providing advice to the Platform, or in carrying out the duties of the Data Access Governance Committee. An interest can be financial, business, research, research funding, intellectual property interest, public statements, positions held, employment, consultancies, directorships or any other interest.

2.  Declaring conflicts: DAGC members shall declare any interests in advance of joining the DAGC using a Conflicts of Interests form. This will be reviewed annually. The Chair of the DAGC will seek verbal confirmation at the start of any meeting that the Declaration of Interests of each member is current and up to date, and in respect to the items of business on the agenda. It is the duty of each member of the DAGC to declare interests not only at the start of meetings but as and when they arise.

3.  Managing conflicts of interest: In assessing declared interests, the DAGC Chair shall balance the nature, type and magnitude of the individual's interest and therefore the degree to which the interest may be reasonably expected to influence his or her judgment against the adequacy of measures/options available to protect the independence and integrity of the decision-making process with the Platform.

4.  Should any conflict of interest arise, these shall be managed using the possible courses of action listed below:

    -   Recommend that the concerned individual fully participate in the meeting or activity and any decision-making;
    -   Recommend that the concerned individual participate in the deliberations, but be recused from making any decisions, on the relevant matter under consideration;
    -   Recommend that the concerned individual do not participate in both the deliberations and the decision-making on the relevant matter under consideration.
    -   Recommend that the individual is not allowed to serve on a governance committee or Secretariat.

5.  Applications from persons associated with the Secretariat, DAGC members, previous members/representatives or associated persons will be defined as a conflict of interest and managed using the options above by the DAGC chair.

## ODAP DAGC review process and voting

1.  When meeting to approve information governance policies and processes, the DAGC shall use best endeavours to take decisions by consensus (meaning all those present in the meeting agree). If consensus on any decision cannot be reached, and unless the DAGC decides otherwise, its decisions shall be taken by a simple majority. Where there is no majority, the Chair shall have the casting vote. Each individual member has one vote.

2.  When asked to support the Lead Institute on deciding whether a request for access is within the scope of ODAP, or reviewing the scientific quality and suitability of a proposal for the platform, the DAGC will refer to the scope and review processes defined in ODAP documentation shared with the Committee. Members can vote to approve or reject a request for access as in or out of scope. Votes to approve or reject must be accompanied by a rationale. All votes and rationale will be visible to all members.


## Reporting structure and escalation process

1.  The ODAP DAGC acts in an advisory role to the University of Edinburgh. In the event of a dispute or serious issue arising, which cannot be resolved by the ODAP DAGC Chair and PI of ODAP, the escalation process will be the responsibility of the Lead Institute, who will conduct an independent investigation and devise an action plan to resolve the issue. This process will be followed for all disputes or issues whether originating within ODAP DAGC or from an external source (e.g. a complaint by a researcher).

## Terms of reference and Information Governance process review

1.  The ODAP DAGC will review its Terms of Reference and the other ODAP information governance processes annually, with the next review due in autumn 2023.

# Members

## Chair

Professor David Crossman University of St Andrews

## Data Contributors

-   ODAP Principal Investigator: Professor Kenny Baillie, University of Edinburgh
-   COVID-19 Genomics UK Consortium (COG-UK): Professor Sharon Peacock, University of Cambridge
-   ICNARC: Professor Kathy Rowan, Intensive Care National Audit & Research Centre (ICNARC)
-   ISARIC4C: Professor Calum Semple, University of Liverpool
-   GenOMICC: Dr Clark Russell, University of Edinburgh
-   PHOSP-COVID: Professor Louise Wain, University of Leicester
-   HEAL-COVID: Professor Charlotte Summers, University of Cambridge

## Public Health Agencies

-   UK Health Security Agency (UK HSA): Dr Johanna Hutchinson, Deputy: Dr Ian Harrison
-   Public Health Scotland: Carole Morris
-   Health and Social Care Northern Ireland: Dr Declan Bradley
-   Welsh Government: Felicity Bennée, Deputy: Dr Christopher Williams

## Other scientific members

-   Edinburgh Parallel Computing Centre: Professor Mark Parsons University of Edinburgh
-   CLIMB-COVID: Professor Tom Connor Cardiff University
-   Health Data Research UK: Professor Andrew Morris

## Lay Representatives

-   Lay Representative 1 TBC
-   Lay Representative 2 TBC

## Secretariat

-   Lead Institute/University of Edinburgh Moni Choudhury, Kat Webster, Jack Oliver

## Observers

-   Lead Institute (University of Edinburgh) Rob Baxter
-   Health Data Research UK Lara Edwards, Edel McNamara, Frances Burns



